name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # Dagelijks
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Set git identity
        run: |
          git config --global user.name "BereKanters"
          git config --global user.email "berekanters@users.noreply.github.com"

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_username: BereKanters
          committer_email: berekanters@users.noreply.github.com
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
